/**
 * Data Store Registry — Static metadata for all persisted data stores
 *
 * Describes every JSON file and directory that the app writes to disk,
 * including lifecycle classification, retention defaults, and capabilities.
 */

import type { DataLifecycle, DataStoreEntry } from '@shared/types';

// ── Lifecycle constants (avoids sonarjs/no-duplicate-string) ────

const TRANSIENT: DataLifecycle = 'transient';
const SHORT_LIVED: DataLifecycle = 'short-lived';
const PERSISTENT: DataLifecycle = 'persistent';

/**
 * Complete registry of all data stores managed by the application.
 *
 * Each entry describes one file or directory in the user-data directory,
 * its lifecycle, default retention policy, and capability flags.
 */
export const DATA_STORE_REGISTRY: DataStoreEntry[] = [
  // ── Short-lived / Transient stores ────────────────────────────

  {
    id: 'error-log',
    label: 'Error Log',
    description: 'Application error entries collected during runtime',
    filePath: 'error-log.json',
    isDirectory: false,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 7, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'planner',
    label: 'Daily Planner',
    description: 'Daily plans stored as one JSON file per date',
    filePath: 'planner/',
    isDirectory: true,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 90, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'email-queue',
    label: 'Email Queue',
    description: 'Queued and failed outbound email retry entries',
    filePath: 'email-queue.json',
    isDirectory: false,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 30, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'briefings',
    label: 'Daily Briefings',
    description: 'Cached daily briefing summaries',
    filePath: 'briefings.json',
    isDirectory: false,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxItems: 30, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'notifications-cache',
    label: 'Notifications Cache',
    description: 'Cached Slack and GitHub notifications',
    filePath: 'notifications-cache.json',
    isDirectory: false,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxItems: 500, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'progress',
    label: 'Agent Progress',
    description: 'JSONL progress files from agent orchestrator sessions',
    filePath: 'progress/',
    isDirectory: true,
    lifecycle: TRANSIENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 7, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'qa',
    label: 'QA Reports',
    description: 'QA session output and reports from automated testing',
    filePath: 'qa/',
    isDirectory: true,
    lifecycle: TRANSIENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 7, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'logs',
    label: 'Application Logs',
    description: 'Main process log file (already rotated by logger)',
    filePath: 'logs/main.log',
    isDirectory: false,
    lifecycle: SHORT_LIVED,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: true,
    canExport: true,
    sensitive: false,
  },

  // ── Persistent stores (user data) ────────────────────────────

  {
    id: 'notes',
    label: 'Notes',
    description: 'User notes with tags, pinning, and project association',
    filePath: 'notes.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: true,
    defaultRetention: { maxAgeDays: 365, maxItems: 1000, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'alerts',
    label: 'Alerts',
    description: 'System and user alerts for task, agent, and device events',
    filePath: 'alerts.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: true,
    defaultRetention: { maxAgeDays: 90, maxItems: 500, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'ideas',
    label: 'Ideas',
    description: 'Idea board with categories, voting, and project association',
    filePath: 'ideas.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: true,
    defaultRetention: { maxAgeDays: 365, maxItems: 1000, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'milestones',
    label: 'Milestones',
    description: 'Project milestones and completion tracking',
    filePath: 'milestones.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'changelog',
    label: 'Changelog',
    description: 'Automatically recorded project changes',
    filePath: 'changelog.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'fitness-workouts',
    label: 'Fitness Workouts',
    description: 'Logged workouts with exercises and duration',
    filePath: 'fitness/workouts.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 365, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'fitness-measurements',
    label: 'Fitness Measurements',
    description: 'Body measurements (weight, body fat, etc.) deduplicated by date',
    filePath: 'fitness/measurements.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'fitness-goals',
    label: 'Fitness Goals',
    description: 'User-defined fitness goals with progress tracking',
    filePath: 'fitness/goals.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'captures',
    label: 'Quick Captures',
    description: 'Dashboard quick-capture text entries',
    filePath: 'captures.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 365, maxItems: 500, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'assistant-watches',
    label: 'Assistant Watches',
    description: 'Persistent subscription triggers for proactive notifications',
    filePath: 'assistant-watches.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { maxAgeDays: 90, enabled: true },
    canClear: true,
    canExport: true,
    sensitive: false,
  },

  // ── Config stores (no retention, user-managed) ────────────────

  {
    id: 'settings',
    label: 'Settings',
    description: 'Application settings and user preferences',
    filePath: 'settings.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'email-config',
    label: 'Email Configuration',
    description: 'SMTP email provider configuration',
    filePath: 'email-config.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'briefing-config',
    label: 'Briefing Configuration',
    description: 'Daily briefing generation settings',
    filePath: 'briefing-config.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: true,
    sensitive: false,
  },
  {
    id: 'hub-config',
    label: 'Hub Configuration',
    description: 'Hub server connection settings and device registration',
    filePath: 'hub-config.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: false,
    sensitive: false,
  },
  {
    id: 'notification-config',
    label: 'Notification Configuration',
    description: 'Notification watcher settings (Slack, GitHub polling)',
    filePath: 'notification-watcher-config.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: false,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: true,
    sensitive: false,
  },

  // ── Sensitive stores (encrypted, no export) ───────────────────

  {
    id: 'oauth-tokens',
    label: 'OAuth Tokens',
    description: 'OAuth access and refresh tokens (encrypted with safeStorage)',
    filePath: 'oauth-tokens.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: true,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: false,
    sensitive: true,
  },
  {
    id: 'oauth-providers',
    label: 'OAuth Providers',
    description: 'OAuth client credentials per provider (encrypted with safeStorage)',
    filePath: 'oauth-providers.json',
    isDirectory: false,
    lifecycle: PERSISTENT,
    encrypted: true,
    hubSynced: false,
    defaultRetention: { enabled: false },
    canClear: false,
    canExport: false,
    sensitive: true,
  },
];
