import type { ThemeTokens } from '../types/settings';

/** All CSS variable token keys that make up a color theme (33 total) */
export const THEME_TOKEN_KEYS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'sidebar',
  'sidebar-foreground',
  'popover',
  'popover-foreground',
  'success',
  'success-foreground',
  'warning',
  'warning-foreground',
  'info',
  'info-foreground',
  'error',
  'error-light',
  'success-light',
  'warning-light',
  'info-light',
  'shadow-focus',
] as const;

/** Default light theme token values — extracted from :root in globals.css */
export const DEFAULT_LIGHT_TOKENS: ThemeTokens = {
  background: '#f2f2ed',
  foreground: '#0b0b0f',
  card: '#ffffff',
  'card-foreground': '#0b0b0f',
  primary: '#a5a66a',
  'primary-foreground': '#0b0b0f',
  secondary: '#e8e8e3',
  'secondary-foreground': '#0b0b0f',
  muted: '#edede8',
  'muted-foreground': '#5c6974',
  accent: '#efefe0',
  'accent-foreground': '#a5a66a',
  destructive: '#d84f68',
  'destructive-foreground': '#ffffff',
  border: '#deded9',
  input: '#deded9',
  ring: '#a5a66a',
  sidebar: '#ffffff',
  'sidebar-foreground': '#0b0b0f',
  popover: '#ffffff',
  'popover-foreground': '#0b0b0f',
  success: '#4ebe96',
  'success-foreground': '#ffffff',
  'success-light': '#e0f5ed',
  warning: '#d2d714',
  'warning-foreground': '#0b0b0f',
  'warning-light': '#f5f5d0',
  info: '#479ffa',
  'info-foreground': '#ffffff',
  'info-light': '#e8f4ff',
  error: '#d84f68',
  'error-light': '#fce8ec',
  'shadow-focus': '0 0 0 3px rgba(165, 166, 106, 0.2)',
};

/** Default dark theme token values — extracted from .dark in globals.css */
export const DEFAULT_DARK_TOKENS: ThemeTokens = {
  background: '#0b0b0f',
  foreground: '#e6e6e6',
  card: '#121216',
  'card-foreground': '#e6e6e6',
  primary: '#d6d876',
  'primary-foreground': '#0b0b0f',
  secondary: '#1a1a1f',
  'secondary-foreground': '#e6e6e6',
  muted: '#1a1a1f',
  'muted-foreground': '#868f97',
  accent: '#2a2a1f',
  'accent-foreground': '#d6d876',
  destructive: '#ff5c5c',
  'destructive-foreground': '#0b0b0f',
  border: '#232323',
  input: '#232323',
  ring: '#d6d876',
  sidebar: '#0e0e12',
  'sidebar-foreground': '#e6e6e6',
  popover: '#1a1a1f',
  'popover-foreground': '#e6e6e6',
  success: '#4ebe96',
  'success-foreground': '#0b0b0f',
  'success-light': '#1a2924',
  warning: '#d2d714',
  'warning-foreground': '#0b0b0f',
  'warning-light': '#262618',
  info: '#479ffa',
  'info-foreground': '#0b0b0f',
  'info-light': '#1a2230',
  error: '#ff5c5c',
  'error-light': '#2a1a1a',
  'shadow-focus': '0 0 0 2px rgba(214, 216, 118, 0.2)',
};

// TODO: Remove after Task #4 updates ColorThemeSection.tsx — kept for backward compat
export const COLOR_THEMES = ['default'] as const;

export type ColorTheme = (typeof COLOR_THEMES)[number];

export const COLOR_THEME_LABELS: Record<ColorTheme, string> = {
  default: 'Default',
} as const;
