/**
 * IPC Contract — Backward-Compatible Re-export
 *
 * The actual contracts are now in src/shared/ipc/<domain>/ folders.
 * Each domain folder contains its own schemas, invoke contract, and event contract.
 *
 * The root barrel at src/shared/ipc/index.ts merges all domain contracts
 * into the unified ipcInvokeContract and ipcEventContract objects.
 *
 * Import from '@shared/ipc-contract' (this file) for the merged contract,
 * or from individual domain folders for domain-specific schemas.
 */
export {
  // Merged contracts
  ipcEventContract,
  ipcInvokeContract,
  // Utility types
  type EventChannel,
  type EventPayload,
  type InvokeChannel,
  type InvokeInput,
  type InvokeOutput,
  // ── Schema re-exports (alphabetical by domain) ──
  // agents
  AgentPhaseSchema,
  AgentSessionStatusSchema,
  OrchestratorSessionSchema,
  // assistant
  AssistantActionSchema,
  AssistantContextSchema,
  AssistantResponseSchema,
  CommandHistoryEntrySchema,
  IntentTypeSchema,
  WebhookCommandSchema,
  WebhookCommandSourceContextSchema,
  // auth
  AuthTokensSchema,
  LoginInputSchema,
  LoginOutputSchema,
  RefreshInputSchema,
  RefreshOutputSchema,
  RegisterInputSchema,
  RegisterOutputSchema,
  UserSchema,
  // briefing
  AgentActivitySummarySchema,
  BriefingConfigSchema,
  DailyBriefingSchema,
  SuggestionActionSchema,
  SuggestionSchema,
  SuggestionTypeSchema,
  TaskSummarySchema,
  // claude
  ClaudeConversationSchema,
  ClaudeMessageSchema,
  ClaudeSendMessageResponseSchema,
  ClaudeStreamChunkSchema,
  ClaudeTokenUsageSchema,
  // common
  SuccessResponseSchema,
  SuccessWithErrorSchema,
  TokenUsageSchema,
  // email
  EmailAttachmentSchema,
  EmailSchema,
  EmailSendResultSchema,
  EmailStatusSchema,
  QueuedEmailSchema,
  SmtpConfigSchema,
  SmtpProviderSchema,
  // fitness
  BodyMeasurementSchema,
  ExerciseSchema,
  ExerciseSetSchema,
  FitnessGoalSchema,
  FitnessGoalTypeSchema,
  FitnessStatsSchema,
  MeasurementSourceSchema,
  WeightUnitSchema,
  WorkoutSchema,
  WorkoutTypeSchema,
  // git
  GitBranchSchema,
  GitStatusSchema,
  RepoStructureSchema,
  WorktreeSchema,
  // github
  GitHubIssueSchema,
  GitHubLabelSchema,
  GitHubNotificationSchema,
  GitHubPullRequestSchema,
  // health
  ErrorCategorySchema,
  ErrorContextSchema,
  ErrorEntrySchema,
  ErrorSeveritySchema,
  ErrorStatsSchema,
  ErrorTierSchema,
  HealthStatusSchema,
  ServiceHealthSchema,
  ServiceHealthStatusSchema,
  // hub
  HubConfigOutputSchema,
  HubConnectionStatusSchema,
  HubStatusOutputSchema,
  HubSyncOutputSchema,
  // misc (alerts, changelog, devices, ideas, insights, merge, milestones, notes, screen, voice, workspaces)
  AlertLinkedToSchema,
  AlertSchema,
  AlertTypeSchema,
  ChangeCategorySchema,
  ChangelogEntrySchema,
  ChangeTypeSchema,
  DeviceCapabilitiesSchema,
  DeviceSchema,
  DeviceTypeSchema,
  IdeaCategorySchema,
  IdeaSchema,
  IdeaStatusSchema,
  InsightMetricsSchema,
  InsightTimeSeriesSchema,
  MergeDiffFileSchema,
  MergeDiffSummarySchema,
  MergeResultSchema,
  MilestoneSchema,
  MilestoneStatusSchema,
  MilestoneTaskSchema,
  NoteSchema,
  ProjectInsightsSchema,
  RecurringConfigSchema,
  ScreenPermissionStatusSchema,
  ScreenSourceSchema,
  ScreenshotSchema,
  TaskDistributionSchema,
  VoiceConfigSchema,
  VoiceInputModeSchema,
  WorkspaceSchema,
  WorkspaceSettingsSchema,
  // notifications
  GitHubNotificationTypeSchema,
  GitHubWatcherConfigSchema,
  NotificationFilterSchema,
  NotificationMetadataSchema,
  NotificationSchema,
  NotificationSourceSchema,
  NotificationTypeSchema,
  NotificationWatcherConfigSchema,
  SlackNotificationTypeSchema,
  SlackWatcherConfigSchema,
  // planner
  DailyPlanSchema,
  ScheduledTaskSchema,
  TimeBlockSchema,
  TimeBlockTypeSchema,
  WeeklyReviewSchema,
  WeeklyReviewSummarySchema,
  // projects
  ChildRepoSchema,
  ProjectSchema,
  RepoDetectionResultSchema,
  RepoTypeSchema,
  SubProjectSchema,
  // qa
  QaIssueSeveritySchema,
  QaIssueSchema,
  QaModeSchema,
  QaReportSchema,
  QaResultSchema,
  QaScreenshotSchema,
  QaSessionSchema,
  QaSessionStatusSchema,
  QaVerificationResultSchema,
  QaVerificationSuiteSchema,
  // settings
  AppSettingsSchema,
  ProfileSchema,
  WebhookConfigSchema,
  // tasks
  EstimatedEffortSchema,
  ExecutionPhaseSchema,
  ExecutionProgressSchema,
  GithubIssueImportSchema,
  HubTaskPrioritySchema,
  HubTaskProgressSchema,
  HubTaskSchema,
  HubTaskStatusSchema,
  SubtaskSchema,
  SuggestedPrioritySchema,
  TaskDecompositionResultSchema,
  TaskDraftSchema,
  TaskSchema,
  TaskStatusSchema,
  TaskSuggestionSchema,
  // terminals
  TerminalSessionSchema,
} from './ipc';
