/**
 * Assistant IPC — Barrel Export
 *
 * Re-exports all assistant-related schemas (command bar, Claude SDK,
 * email, notifications, GitHub, briefings, webhooks) and contract definitions.
 */

export {
  AgentActivitySummarySchema,
  AssistantActionSchema,
  AssistantContextSchema,
  AssistantResponseSchema,
  BriefingConfigSchema,
  ClaudeConversationSchema,
  ClaudeMessageSchema,
  ClaudeSendMessageResponseSchema,
  ClaudeStreamChunkSchema,
  ClaudeTokenUsageSchema,
  CommandHistoryEntrySchema,
  DailyBriefingSchema,
  EmailAttachmentSchema,
  EmailSchema,
  EmailSendResultSchema,
  EmailStatusSchema,
  GitHubIssueSchema,
  GitHubLabelSchema,
  GitHubNotificationSchema,
  GitHubNotificationTypeSchema,
  GitHubPullRequestSchema,
  GitHubWatcherConfigSchema,
  IntentTypeSchema,
  NotificationFilterSchema,
  NotificationMetadataSchema,
  NotificationSchema,
  NotificationSourceSchema,
  NotificationTypeSchema,
  NotificationWatcherConfigSchema,
  QueuedEmailSchema,
  SlackNotificationTypeSchema,
  SlackWatcherConfigSchema,
  SmtpConfigSchema,
  SmtpProviderSchema,
  SuggestionActionSchema,
  SuggestionSchema,
  SuggestionTypeSchema,
  TaskSummarySchema,
  WebhookCommandSchema,
  WebhookCommandSourceContextSchema,
} from './schemas';

export {
  assistantEvents,
  assistantInvoke,
  briefingEvents,
  briefingInvoke,
  calendarInvoke,
  claudeInvoke,
  emailEvents,
  emailInvoke,
  githubEvents,
  githubInvoke,
  mcpInvoke,
  notificationEvents,
  notificationsInvoke,
  rateLimitEvents,
  spotifyInvoke,
  timeInvoke,
} from './contract';
